sudo: false
language: node.js
notifications:
  irc:
    channels:
      - "irc.w3.org#sysreq"
    skip_join: true
install:
 - wget https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.0-beta-3/browsermob-proxy-2.1.0-beta-3-bin.zip
 - unzip browsermob-proxy-2.1.0-beta-3-bin.zip
 - browsermob-proxy-2.1.0-beta-3/bin/browsermob-proxy &
 - npm install
 - ./.travis-setup.sh
script:
 - npm test
